### ISSUE TITLE
How is this different from https://github.com/DeepReading/DeepReading/wiki/Resources ?

### ISSUE THREAD

**Issue by faizankshaikh** [DeepReading/DeepLearningResources#1]

**Comment by anweshknayak** [comment]
If you want I can delete this. But messing all stuffs at one place makes it confusing. Better be a separate thing. where you can redirect it here. And it might help others too without putting much effort. You can use wiki for keeping track of events timelines discussions articles.

**Comment by faizankshaikh** [comment]
agreed
